version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:13.2
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"

networks:
  backend:

